Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -129,7 +129,16 @@ jobs:
         env:
           MAVEN_OPTS: "${{ matrix.jvm_flags }}"
 
-
+      - name: Verify JaCoCo Report Generation
+        run: |
+          if [ ! -f target/site/jacoco/index.html ]; then
+            echo "JaCoCo report not found. Attempting to generate the report."
+            ./mvnw clean verify jacoco:report || { echo "Failed to generate JaCoCo report"; exit 1; }
+            echo "JaCoCo report generation complete."
+          else
+            echo "JaCoCo report already exists. Skipping generation."
+          fi
+          
       - name: Display Coverage Summary
         run: |
           if [ -f target/site/jacoco/index.html ]; then
