Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -145,17 +145,19 @@ jobs:
 
       - name: Generate JaCoCo Report
         run: |
-          echo "Generating JaCoCo report using exec file: ${jacoco_exec_file}"
-          ./mvnw jacoco:report -Djacoco.dataFile=${jacoco_exec_file} || { echo "Error generating JaCoCo report"; exit 1; }
-          default_report_dir="target/site/jacoco"
+         sanitized_flag=$(echo "${{ matrix.jvm_flags }}" | sed 's/[^-a-zA-Z0-9+._]/_/g' | tr ' ' '_')
+         jacoco_exec_file="target/jacoco_${sanitized_flag}.exec"
+         echo "Generating JaCoCo report using exec file: ${jacoco_exec_file}"
+         ./mvnw -X jacoco:report -Djacoco.dataFile=${jacoco_exec_file}
 
-          if [ -d "${default_report_dir}" ]; then
-             echo "JaCoCo report generated successfully. You can find the report at: ${default_report_dir}/index.html"
-             ls -l ${default_report_dir}
-          else
-             echo "JaCoCo report directory not found. Report generation may have failed."
-             exit 1
-          fi
+         default_report_dir="target/site/jacoco"
+         if [ -d "${default_report_dir}" ]; then
+            echo "JaCoCo report generated successfully. You can find the report at: ${default_report_dir}/index.html"
+            ls -l ${default_report_dir}
+         else
+            echo "JaCoCo report directory not found. Report generation may have failed."
+            exit 1
+         fi
 
       - name: Extract Coverage Percentage
         run: |
