Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -126,11 +126,15 @@ jobs:
       - name: Run Tests with JVM Flag
         run: |
           echo "Running tests with JVM Flag: ${{ matrix.jvm_flags }}"
-          MAVEN_OPTS="${{ matrix.jvm_flags }}" ./mvnw clean test -Djava.awt.headless=true
+          jacoco_agent_path=$(find ~/.m2 -name "jacoco-agent*.jar" | head -n 1)
+          if [ -z "$jacoco_agent_path" ]; then
+            echo "JaCoCo agent not found. Please ensure that JaCoCo is configured as a Maven dependency."
+            exit 1
+         fi
+         MAVEN_OPTS="-javaagent:${jacoco_agent_path} ${matrix.jvm_flags}" ./mvnw clean test -Djava.awt.headless=true
           
       - name: Generate JaCoCo Report
         run: |
-         echo "Generating JaCoCo report for JVM Flag: ${{ matrix.jvm_flags }}"
          sanitized_flag=$(echo "${{ matrix.jvm_flags }}" | sed 's/[^a-zA-Z0-9]/_/g')
          ./mvnw jacoco:report -Djacoco.outputDirectory=target/site/jacoco_${sanitized_flag}
 
